apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    app: client
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client
        version: v1
    spec:
      containers:
      - image: gcr.io/nandanks-151422/client
        imagePullPolicy: Always
        name: client
        resources:
          requests:
            cpu: 100m
      nodeSelector:
        cloud.google.com/gke-nodepool: apps            