apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: orders
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orders
        version: v1
    spec:
      containers:
      - image: gcr.io/nandanks-151422/orders
        imagePullPolicy: IfNotPresent
        name: orders
        ports:
        - containerPort: 8080
        env:
          - name: INVENTORY
            value: "http://inventory.apps.svc.cluster.local:8080"             
        resources:
          requests:
            cpu: 100m
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      nodeSelector:
        cloud.google.com/gke-nodepool: apps          