# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: orders
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      annotations:
        # exlude health check port for envoy filter
        readiness.status.sidecar.istio.io/applicationPorts: "8090"
        # rewrite http probe
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: orders
        version: v1
    spec:
      containers:
      - image: gcr.io/project-id/orders
        imagePullPolicy: IfNotPresent
        name: orders
        ports:
        - containerPort: 8080
        - containerPort: 8090
        env:
          - name: INVENTORY
            value: "http://inventory.apps.svc.cluster.local:8080"
        resources:
          requests:
            cpu: 100m
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 5
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - apps
            weight: 100
