apiVersion: batch/v1
kind: Job
metadata:
  name: pod-cleanup
  namespace: apps 
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: daily-cleanup-sa
      containers:
      - name: daily-cleanup
        image: gcr.io/srinandans-apigee/daily-cleanup
        imagePullPolicy: Always
      restartPolicy: Never
