apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: daily-cleanup-pods-role-binding
  namespace: apps
subjects:
  - kind: ServiceAccount
    name: daily-cleanup-sa
    namespace: apps
roleRef:
  kind: ClusterRole
  name: daily-evicted-pod-cleanup-role
  apiGroup: rbac.authorization.k8s.io
