apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daily-evicted-pod-cleanup-role
  namespace: apps
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
