apiVersion: v1
kind: Service
metadata:
  name: tracking
  labels:
    app: tracking
spec:
  ports:
  - port: 50051
    name: http
  selector:
    app: tracking
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tracking
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tracking
        version: v1
    spec:
      containers:
      - image: gcr.io/nandanks-151422/tracking
        imagePullPolicy: IfNotPresent
        name: tracking
        ports:
        - containerPort: 50051
        env:
          - name: DEBUG
            value: "true"             
        resources:
          requests:
            cpu: 100m
      nodeSelector:
        cloud.google.com/gke-nodepool: apps          