# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: keyservice
  labels:
    app: keyservice
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: keyservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keyservice
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        readiness.status.sidecar.istio.io/applicationPorts: "8080"
        readiness.status.sidecar.istio.io/initialDelaySeconds: "20"
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: keyservice
        version: v1
    spec:
      serviceAccountName: apps    
      containers:
        - image: keyservice
          imagePullPolicy: IfNotPresent
          name: keyservice
          ports:
            - containerPort: 8080
            - containerPort: 8090
          env:
            - name: DEBUG
              value: 'false'
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"               
          securityContext:
            runAsNonRoot: true
            runAsUser: 20001
            runAsGroup: 20000
            allowPrivilegeEscalation: false
            capabilities:
              # https://istio.io/latest/docs/ops/deployment/requirements/
              add:
                - NET_ADMIN
                - NET_RAW
              drop:
                - ALL
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 50m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8090
            initialDelaySeconds: 20
            periodSeconds: 5
          volumeMounts:
            - mountPath: /policy-secret
              name: policy-secret
              readOnly: true
      #NOTE: This is not working with Istio. If using Istio, comment these lines
      #serviceAccount: app-sa
      #serviceAccountName: app-sa
      volumes:
      - name: policy-secret
        secret:
          defaultMode: 420
          secretName: nandanks-serverless-prod1-policy-secret
          #optional: true
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: cloud.google.com/gke-nodepool
                    operator: In
                    values:
                      - apps
              weight: 100