apiVersion: v1
kind: Service
metadata:
  name: orders-gql
  labels:
    app: orders-gql
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: orders-gql
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orders-gql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orders-gql
        version: v1
    spec:
      containers:
      - image: gcr.io/nandanks-151422/orders-gql
        imagePullPolicy: IfNotPresent
        name: orders-gql
        ports:
        - containerPort: 8080
        env:
          - name: DEBUG
            value: "true"     
          - name: ORDERS
            value: "http://orders.apps.svc.cluster.local:8080"
        resources:
          requests:
            cpu: 100m
      nodeSelector:
        cloud.google.com/gke-nodepool: apps          