apiVersion: v1
kind: Service
metadata:
  name: load-test
  labels:
    app: load-test
spec:
  clusterIP: None
  selector:
    app: load-test
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: load-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: load-test
    spec:
      containers:
      - image: fortio/fortio
        imagePullPolicy: Always
        name: load-test
        ports:
        - containerPort: 8080
        env:
          - name: API_KEY
            value: "xxxx"   #set actual api key
        resources:
          requests:
            cpu: 250m
        args:
        - load
        - -t
        - "0" #run forever
        - -qps
        - "1"
        - -quiet
        - -H
        - "x-api-key: $API_KEY"        
        - https://httpbin.org/get
      nodeSelector:
        cloud.google.com/gke-nodepool: apps